{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x00000254FC6CC5F8>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "e237fa40-3014-4e7e-a800-8892cce33f08-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b634cf0a-d4bf-49bd-a48d-cb0b488b2aa1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2009994d-a4ca-478b-af01-8b5c2c0ae5d7-attachment.txt", "type": "text/plain"}], "start": 1651787570243, "stop": 1651787763347, "uuid": "a17662bd-ed06-406c-bfff-8947715821e4", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}