{"name": "test_mcc", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_MCC_incarnet\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_MCC_incarnet', 'mcc')", "trace": "self = <Test_MT.TestOther object at 0x0000028386C3D7F0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_MCC_incarnet\")\n    def test_mcc (self):\n>       assert AutoTest(number, mac, name, '_P_MCC_incarnet', 'mcc') == True, \"Ошибка в ходе выполнения теста \" \\\n                                                                              \"_P_MCC_incarnet\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_MCC_incarnet\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_MCC_incarnet', 'mcc')\n\nTest_MT.py:111: AssertionError"}, "attachments": [{"name": "log", "source": "2cf810fe-f16c-40a6-89ea-3b57359c2c9e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ecb41159-23e4-4589-8d4c-f1a15eed08bf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "70cd3869-17aa-45b0-9d56-e89e856d5bf2-attachment.txt", "type": "text/plain"}], "start": 1652100732660, "stop": 1652100871342, "uuid": "100e1bf1-4f9f-4834-9b60-2bb15ef16548", "historyId": "ea63307a143029c49ed17708f2a8e8fd", "testCaseId": "2d68106bb6941280f492c89799ca2402", "fullName": "Test_MT.TestOther#test_mcc", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_MCC_incarnet"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "9060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}