{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x000001DC6085DD68>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "193b04b7-b0ca-442d-ac94-2d0413cf6a85-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "27d687c4-2dc0-4769-8628-24b164316b7b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1d489830-f134-4ffe-802a-cd1fe76fe2b9-attachment.txt", "type": "text/plain"}], "start": 1651220974819, "stop": 1651221127474, "uuid": "9be9e10c-0701-4aad-a06e-8ba00dd7067e", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "16776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}