{"name": "test_eos_enforta", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')", "trace": "self = <Test_MT.TestEOS object at 0x0000029699640518>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_enforta_street\")\n    def test_eos_enforta (self):\n>       assert AutoTest(number, mac, name, '_P_dit_enforta_street', 'enforta') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                        \" теста _P_dit_enforta_street\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')\n\nTest_MT.py:55: AssertionError"}, "attachments": [{"name": "log", "source": "a8398530-bcbf-4c80-9060-96484946f840-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2ba8c276-90c1-43e7-9ff7-8b0b4d43e23a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f40bd6d2-01fe-44ae-adaf-9b33fff5124c-attachment.txt", "type": "text/plain"}], "start": 1651651279963, "stop": 1651651402115, "uuid": "4ef216f6-ad9b-47da-859a-d4f068fdf758", "historyId": "9da6db121f31cf0f47b5e1d44b4f28a9", "testCaseId": "b08c90c53b7a3d9ae56ab77b48c41ae2", "fullName": "Test_MT.TestEOS#test_eos_enforta", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_dit_enforta_street"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "9328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}