{"name": "test_eos_enforta", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')", "trace": "self = <Test_MT.TestEOS object at 0x000001B9C87A1438>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_enforta_street\")\n    def test_eos_enforta (self):\n>       assert AutoTest(number, mac, name, '_P_dit_enforta_street', 'enforta') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                        \" теста _P_dit_enforta_street\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')\n\nTest_MT.py:55: AssertionError"}, "attachments": [{"name": "log", "source": "adee7ac7-6b86-4870-b133-e478b9858d4a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "7bd76f60-3629-4232-abbc-0a7627ad9cdc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8f6b947a-cf7d-4a73-b88c-1d1527720c1c-attachment.txt", "type": "text/plain"}], "start": 1651171969256, "stop": 1651172088549, "uuid": "1e7c5286-f215-4fab-97ee-d2ae21d922e8", "historyId": "9da6db121f31cf0f47b5e1d44b4f28a9", "testCaseId": "b08c90c53b7a3d9ae56ab77b48c41ae2", "fullName": "Test_MT.TestEOS#test_eos_enforta", "labels": [{"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "story", "value": "Авторизация _P_dit_enforta_street"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}