{"name": "test_eos_almatel", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_almatel\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_almatel', 'almatel')", "trace": "self = <Test_MT.TestEOS object at 0x000001B9D1F77CC0>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_almatel\")\n    def test_eos_almatel (self):\n>       assert AutoTest(number, mac, name, '_P_dit_almatel', 'almatel') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                 \" теста _P_dit_almatel\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_almatel\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_almatel', 'almatel')\n\nTest_MT.py:80: AssertionError"}, "attachments": [{"name": "log", "source": "97cbbcc1-fe71-4b4f-8196-1e763649de4a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f144bd71-8c01-4a19-b4d5-dd0d4837ace7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8027bf9f-7857-41a5-b1eb-4733e88186be-attachment.txt", "type": "text/plain"}], "start": 1651172266214, "stop": 1651172531457, "uuid": "10989856-70cf-491b-a909-97d702f21ed8", "historyId": "c5bf391e63a923465e2d1bd52a6989ba", "testCaseId": "62017347374c030da37590ffd1021500", "fullName": "Test_MT.TestEOS#test_eos_almatel", "labels": [{"name": "story", "value": "Авторизация _P_dit_almatel"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}