{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x00000195FDC1F978>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "f29da33d-d439-415e-91df-6f97520a3577-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d4af8d74-8535-49c5-a33e-d459587dfd15-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "faf725c0-9407-4a09-aee0-24beb7c93a05-attachment.txt", "type": "text/plain"}], "start": 1652046862015, "stop": 1652047056674, "uuid": "f21554f1-9d8a-4046-ba3f-1f8ab7d24651", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "8516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}