{"name": "test_eos_enforta", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')", "trace": "self = <Test_MT.TestEOS object at 0x000001FC66E01320>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_dit_enforta_street\")\n    def test_eos_enforta (self):\n>       assert AutoTest(number, mac, name, '_P_dit_enforta_street', 'enforta') == True, \"Ошибка в ходе выполнения\" \\\n                                                                                        \" теста _P_dit_enforta_street\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_dit_enforta_street\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_dit_enforta_street', 'enforta')\n\nTest_MT.py:55: AssertionError"}, "attachments": [{"name": "log", "source": "6b8bc8a2-4399-4a2d-b24e-f9eec53b1273-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4e0e9667-becb-4153-87bc-26fc1da38c51-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c90bfd08-e946-47f7-9184-11dab329d252-attachment.txt", "type": "text/plain"}], "start": 1652175464461, "stop": 1652175624749, "uuid": "c06fe6c2-4a5a-44ce-8553-4dae06a0ffd1", "historyId": "9da6db121f31cf0f47b5e1d44b4f28a9", "testCaseId": "b08c90c53b7a3d9ae56ab77b48c41ae2", "fullName": "Test_MT.TestEOS#test_eos_enforta", "labels": [{"name": "story", "value": "Авторизация _P_dit_enforta_street"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "suite", "value": "Тесты сегментов ЕОС"}, {"name": "subSuite", "value": "TestEOS"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}