{"name": "test_cppk", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста _P_cppk\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_cppk', 'cppk')", "trace": "self = <Test_MT.TestOther object at 0x00000247829332E8>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_cppk\")\n    def test_cppk (self):\n>       assert AutoTest(number, mac, name, '_P_cppk', 'cppk') == True, \"Ошибка в ходе выполнения теста _P_cppk\"\nE       AssertionError: Ошибка в ходе выполнения теста _P_cppk\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_cppk', 'cppk')\n\nTest_MT.py:106: AssertionError"}, "attachments": [{"name": "log", "source": "6363e7c7-84cc-4d32-b0c6-f1eb3e83f9da-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c6869d80-dcea-49e0-92bc-349b60a967a1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "bb5b852e-6356-416e-b4c6-1af2369753f3-attachment.txt", "type": "text/plain"}], "start": 1651668391341, "stop": 1651668802859, "uuid": "167a0432-0ea9-4013-b358-08e3f7801437", "historyId": "e453b87c8e20737f2e5240696f4d8277", "testCaseId": "e3d132f9150e145b9291a771e93e05c0", "fullName": "Test_MT.TestOther#test_cppk", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_cppk"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "13496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}