{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x000001B9D1BCF208>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "cc9de4f3-4378-48a1-9c01-8b2ace3c503b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "57d747ef-8f28-4616-9520-87ff7639bab3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2164bb59-1305-4de3-9b45-c3c1ffd128f5-attachment.txt", "type": "text/plain"}], "start": 1651173253219, "stop": 1651173451300, "uuid": "c3ac89a2-f81a-4a85-8fe9-0fa90efdb695", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "feature", "value": "Тест авторизации"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "7388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}