{"name": "test_bus154", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus154\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')", "trace": "self = <Test_MT.TestOther object at 0x0000028F3F34E748>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_mvf_bus\")\n    def test_bus154(self):\n>       assert AutoTest(number, mac, name, '_P_mvf_bus', 'bus154') == True, \"Ошибка в ходе выполнения теста bus154\"\nE       AssertionError: Ошибка в ходе выполнения теста bus154\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_mvf_bus', 'bus154')\n\nTest_MT.py:129: AssertionError"}, "attachments": [{"name": "log", "source": "867e4393-b15f-4343-aa41-493ee5a21aca-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "44b1e1e3-9051-40bb-ac16-514b1029bf04-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "09c2d506-8f16-4e62-97c7-e6f025fbea22-attachment.txt", "type": "text/plain"}], "start": 1651143942247, "stop": 1651144124938, "uuid": "802d2947-de2e-4854-a815-c2a19f919950", "historyId": "6c3f8a24dd4f4f99790af4fc37371378", "testCaseId": "aa57b99d04c859b0fd67a10830cbc1f3", "fullName": "Test_MT.TestOther#test_bus154", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "story", "value": "Авторизация _P_mvf_bus"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "12656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}