{"name": "test_bus207", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка в ходе выполнения теста bus207\nassert False == True\n +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')", "trace": "self = <Test_MT.TestOther object at 0x000001D05BEF19E8>\n\n    @allure.feature(\"Тест авторизации\")\n    @allure.story(\"Авторизация _P_TTM_v5\")\n    def test_bus207(self):\n>       assert AutoTest(number, mac, name, '_P_TTM_v5', 'bus207') == True, \"Ошибка в ходе выполнения теста bus207\"\nE       AssertionError: Ошибка в ходе выполнения теста bus207\nE       assert False == True\nE        +  where False = AutoTest('be11611b', '60-ab-67-f7-1d-a0', 'XiaomiSE', '_P_TTM_v5', 'bus207')\n\nTest_MT.py:134: AssertionError"}, "attachments": [{"name": "log", "source": "b3f7c7cd-e9d3-4cf4-9cd4-aba7bee85943-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "83bf0d0a-53d8-491e-9ab7-83614df8192c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7686dba6-9c33-4326-9f09-96ddaf644290-attachment.txt", "type": "text/plain"}], "start": 1651798640817, "stop": 1651798841071, "uuid": "1ad87703-3480-43f3-8a39-8c44ceaef4fe", "historyId": "3369cd05539770f0c09511c571a4094b", "testCaseId": "bc0a014b62f50edbcb39f57be6bfbe2a", "fullName": "Test_MT.TestOther#test_bus207", "labels": [{"name": "feature", "value": "Тест авторизации"}, {"name": "story", "value": "Авторизация _P_TTM_v5"}, {"name": "suite", "value": "Тесты основных сегментов сети МТ"}, {"name": "subSuite", "value": "TestOther"}, {"name": "host", "value": "tester"}, {"name": "thread", "value": "5784-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_MT"}]}